# General guidelines
1. Try problems in https://www.practicepython.org/exercise/2014/01/29/01-character-input.html if you need a formal tutorial in Python. Personally, I recommend not looking at the solutions, just at the problems, and google-ing the syntax you need. There is no substitute for playing around with the code trying things out
2. Run each cell by clicking on cell then go to Cell->Run cells. 
3. The purpose of this tutorial is NOT learning algorithms, it's just to be able to use python. I've selected a few problems from other places that I feel cover python basics. 
4. I recommend NOT reading the solutions first. Please try to solve everything on your own (which means you can google syntax). I want everyone to learn to be able to figure Pythonic syntax out as independently as possible. That being said, if you struggle, please post on Learn / office hours
5. Notice an advantage of Jupyter here. I can make my code look much prettier than in a normal file right? This cell I'm typing in is called "Markdown" type and it lets me organize my code by headings, put in thoughts & ideas separate from code
6. These are in addition to the "homework" problems in the slides. I'm sorry, my bad, I actually meant "practice" problems. 
7.

# Variable inertia :p 
Objects in memory stay in memory (unless otherwise told to go away)

In [1]:
print ('Creating variable in this cell block')
x = 10

Creating variable in this cell block

In [2]:
print ('This variable is still available in another cell block ', x)

This variable is still available in another cell block  10

In [0]:
print ('In fact, try closing your notebook (not jupyter), reopen it, and run the next cell ')

In [3]:
print ('x still available even after notebook was closed! Variables STAY in memory unless you "shutdown" jupyters kernel (cpu / heart) specifically ')
print (x)

x still available even after notebook was closed! Variables STAY in memory unless you "shutdown" jupyters kernel (cpu / heart) specifically
10

In [4]:
del x
print ('This will give error because you deleted x ')
print (x)

This will give error because you deleted x

NameError: ignored

In [0]:
print ('Notice that even all the outputs are still on your screen (unless you go to Cell->All Output -> Clear). Wouldnt this be useful if you had output1 in one cell, and output2 in another, and wanted to compared the two? ')

# Lists / Strings

## fullname
1. Read 100 users first and last name
2. Print each users full name, and give them an id.
3. Each id should be 5 digits long. Every id is previous id + 1. For ex: 00001, 00002, 00003, ..., 00100

Notice how I broke this code into different "cells" i.e. code blocks. All the code I run will stay in Jupyter memory i.e. Jupyter will remember you wrote them, and you don't have to keep re running this code everytime you make minor changes in other parts of the code. How does this help? Maybe you want to keep getting the names of 100 people many many times. Why would you want to waste time & RAM to process old code that hasn't changed?

In [0]:
def getFull(a,b):
  res = str(a) + ' ' + str(b)
  return res;

def getFixedLengthId(numId):
  print('Num is was ', numId)
  return format(numId, '05d')

In [8]:
i = 0
while (i < 100):
  print('Reading name for user', i)
  first = input('First Name?: ')
  last = input('Last name?: ')
  full = getFull(first,last)
  print(full)
  print(getFixedLengthId(i))
  i += 1
  print('-'*30)

Reading name for user 0
First Name?: Mohammad
Last name?: Parsa
Mohammad Parsa
Num is was  0
00000
------------------------------
Reading name for user 1
First Name?: John
Last name?: Doe
John Doe
Num is was  1
00001
------------------------------
Reading name for user 2

KeyboardInterrupt: ignored

## Palindromes, sublists, string / list reversals
1. Please see https://www.practicepython.org/exercise/2014/03/12/06-string-lists.html for the problem, solution and examples
2. Note how even reversing a list (or a string), as a short concise solution. Python doesn't like verbose syntax. When in doubt, assume someone out there has found a smart Python-ic way of solving your problem, for example string reversal, and look it up first. 
3. Note how it's easy to even extract sublists from lists (for ex: extract [1, 2, 3] from [6, 4, 5, 1, 2, 3, 5] )

# File management
See https://www.practicepython.org/exercise/2014/11/30/21-write-to-a-file.html . Read only the Discussion portion. Don't try to solve Exercise 21 itself

# Pandas
A fancy library to read csv files (aka tables). Let's you do all sorts of things with the data without you having to bother with writing the code from scratch
1. A little challenge: Figure out how to install pandas on your own. Hint: Google "install pandas using anaconda"
2. Some of the problems were taken from here https://pynative.com/python-pandas-exercise/

## Creating a dataframe (pandas name for a table)

In [11]:
table = [
         ['Abeer','Khan'],
         ['John','Doe']
]
print(table)

[['Abeer', 'Khan'], ['John', 'Doe']]

In [12]:
import pandas as pd
df = pd.DataFrame(table)
print(df)

       0     1
0  Abeer  Khan
1   John   Doe

In [13]:
df

       0     1
0  Abeer  Khan
1   John   Doe

In [0]:
df1 = pd.DataFrame(table, columns=['first','last'])
df2 = pd.DataFrame(table)
df2.columns = ['first','last']

In [16]:
df2

   first  last
0  Abeer  Khan
1   John   Doe

In [0]:
df = df1

## Create third column as full name

In [19]:
df['full'] = df['first'] + " " + df['last']
df

   first  last        full
0  Abeer  Khan  Abeer Khan
1   John   Doe    John Doe

## oops, turns out I actually just wanted last and full columns

In [20]:
df[['first','last']]

   first  last
0  Abeer  Khan
1   John   Doe

In [21]:
df['full']

0    Abeer Khan
1      John Doe
Name: full, dtype: object

## A few automobile dataset manipulations
1. Download https://pynative.com/wp-content/uploads/2019/01/Automobile_data.csv 
2. Read it into python using pandas. I assumed I've downloaded it into the same directory as this notebook

### Read csv file

In [22]:
from google.colab import files
uploaded = files.upload()

Saving Automobile_data.csv to Automobile_data.csv

In [0]:
import io
data = io.BytesIO(uploaded['Automobile_data.csv'])

In [29]:
pd.read_csv(data)

    index      company   body-style  ...  horsepower  average-mileage    price
0       0  alfa-romero  convertible  ...         111               21  13495.0
1       1  alfa-romero  convertible  ...         111               21  16500.0
2       2  alfa-romero    hatchback  ...         154               19  16500.0
3       3         audi        sedan  ...         102               24  13950.0
4       4         audi        sedan  ...         115               18  17450.0
..    ...          ...          ...  ...         ...              ...      ...
56     81   volkswagen        sedan  ...          85               27   7975.0
57     82   volkswagen        sedan  ...          52               37   7995.0
58     86   volkswagen        sedan  ...         100               26   9995.0
59     87        volvo        sedan  ...         114               23  12940.0
60     88        volvo        wagon  ...         114               23  13415.0

[61 rows x 10 columns]

### Solve questions 1, 3, 4, 5, 6, 7, 8
See https://pynative.com/python-pandas-exercise/

## trying out some cool pandas functions - concat
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

In [0]:
df1 = pd.DataFrame([['a',1],['b',2]], columns=['letter','number'])
df2 = pd.DataFrame([['c',3],['d',4]],columns=['letter','number'])

In [31]:
df1

  letter  number
0      a       1
1      b       2

In [32]:
df2

  letter  number
0      c       3
1      d       4

In [33]:
pd.concat([df1,df2],axis=0)

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [34]:
pd.concat([df1,df2],axis=1)

  letter  number letter  number
0      a       1      c       3
1      b       2      d       4

## trying some cool pandas functions - merge, some more concat examples
1. (Relate this to joins in relational algebra)
2. I strongly recommend trying this for merge, concat examples https://chrisalbon.com/python/data_wrangling/pandas_join_merge_dataframe/ --> he has good posts in ML, data science